# Generated by Django 6.0 on 2025-12-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('hometown', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('fighter', 'Fighter'), ('navigator', 'Navigator'), ('cook', 'Cook'), ('doctor', 'Doctor'), ('sniper', 'Sniper'), ('musician', 'Musician'), ('general', 'General Crew')], max_length=20)),
                ('skills', models.TextField()),
                ('reason', models.TextField(help_text='Why do you want to join the Red Hair Pirates?')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
    ]
